/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_commercial.View;

import gestion_commercial.CONNEXION.NewCon;
import java.awt.Container;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Home
 */
public class Entrepots extends javax.swing.JFrame {
NewCon cnx=new NewCon();
       Connection con=cnx.getInstance();
      Statement stmt;  
    DefaultTableModel d =new DefaultTableModel();
    int selectedrow;
    int position=1;
   
    private Object jTextField4;
    private Object Rs;
    /**
     * Creates new form Entrepots
     */
    public Entrepots() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update icon.png"))); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/erase-128.png"))); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Vider");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("<");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(">");
        jButton8.setToolTipText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText(">>");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Exporter");

        jButton11.setText("Importer");

        jLabel2.setText("Numero entropot");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(299, 299, 299)
                                        .addComponent(jButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton6)
                                        .addGap(27, 27, 27)
                                        .addComponent(jButton7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(116, 116, 116)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                            .addComponent(jTextField2)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jButton1)
                                .addGap(39, 39, 39)
                                .addComponent(jButton2)
                                .addGap(28, 28, 28)
                                .addComponent(jButton3)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(50, 50, 50)
                .addComponent(jButton11)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              try {   
   
       stmt = con.createStatement();
           
           String namee = null;
            String display_name = null;
           String description = null;
            Date created_at = null;
          Date updated_at = null;
          
            
                   
         DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            
        DateFormat only_date=new SimpleDateFormat("dd");
        DateFormat only_month=new SimpleDateFormat("MM");
        DateFormat only_year=new SimpleDateFormat("yyyy");
            
      String sql="INSERT INTO  entropots(`id`, `Nom`, `created_at`, `updated_at`) VALUES (NULL,'"+jTextField1.getText()+"','"+df.format(jDateChooser1.getDate())+"','"+df.format(jDateChooser2.getDate())+"')";  

stmt.executeUpdate(sql);
      System.out.println("ENTROPOTS ajoute");
       
 } catch (SQLException ex) {
       Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
  }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {
 DefaultTableModel d = new DefaultTableModel();
    Container cnt = this.getContentPane();
    JTable jtbl = new JTable(d);
      stmt = con.createStatement();
        cnt.setLayout(new FlowLayout(FlowLayout.LEFT));
      
        d.addColumn("Nom");
        d.addColumn("created_at");
        d.addColumn("updated_at");
       
        
          
            ResultSet resultat = stmt.executeQuery( "SELECT * FROM `entropots`");
jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
       }
      
            
            
            
            
            
            
         catch (Exception e) {
            System.out.println(e.getMessage());
        }
   
        this.pack();
  
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {  
            
             stmt = con.createStatement();
            String sql="DELETE FROM `megecbase`.`entropots` WHERE `id`="+jTextField2.getText();
        stmt.executeUpdate(sql); 
           System.out.println("entropots supprimé");
        }catch(Exception e){ System.out.println("les champs vous manque à remplir");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {  
             DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            
        DateFormat only_date=new SimpleDateFormat("dd");
        DateFormat only_month=new SimpleDateFormat("MM");
        DateFormat only_year=new SimpleDateFormat("yyyy");
             stmt = con.createStatement();
            String sql="UPDATE `entropots` SET `Nom`='"+jTextField1.getText()+"'`created_at`='"+df.format(jDateChooser1.getDate())+"',`updated_at`='"+df.format(jDateChooser2.getDate())+"' WHERE `id`="+jTextField2.getText()+"";
            stmt.executeUpdate(sql); 
           System.out.println("role modifié");
        }catch(Exception e){ System.out.println("les champs vous manque à remplir");}
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          try {   int ligne=jTable1.getSelectedRow();
           DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            
        DateFormat only_date=new SimpleDateFormat("dd");
        DateFormat only_month=new SimpleDateFormat("MM");
        DateFormat only_year=new SimpleDateFormat("yyyy");
      //  JOptionPane.showMessageDialog(null, ligne);
     
        String 	Nom=jTable1.getModel().getValueAt(ligne, 1).toString();
        
         
  
        Date 	created_at=df.parse(jTable1.getModel().getValueAt(ligne, 2).toString());
   
           
            Date		updated_at=df.parse(jTable1.getModel().getValueAt(ligne, 3).toString());
            
            String id=jTable1.getModel().getValueAt(ligne,0).toString();
            
             jTextField2.setText(Nom);
             
             
              //jDateChooser1.setDate(created_at);
              // jDateChooser2.setDate(updated_at);
              
              
              System.out.println("gestion_commercial.View.eNTROPOTRS.jTable1MouseClicked()");
             
               } catch (ParseException ex) {
        Logger.getLogger(Roles_view.class.getName()).log(Level.SEVERE, null, ex);
    }
              
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            int ligne = 0;
    //  JOptionPane.showMessageDialog(null, ligne);
    
    String 				Nom=jTable1.getModel().getValueAt(ligne, 1).toString();
    String 				created_at=jTable1.getModel().getValueAt(ligne, 1).toString();
     String 				updated_at=jTable1.getModel().getValueAt(ligne, 1).toString();
    
       jTextField2.setText(Nom);
   
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          position--;
      try {      
          int ligne = position;
           
                  stmt = con.createStatement();
        ResultSet resultat;
   
        resultat = stmt.executeQuery( "SELECT * FROM `entropots`");
   
        
        
       int i = 0;
while (resultat.next()) {
 
i++;
}
i--;



if(position==0){
position=i;
}




    //  JOptionPane.showMessageDialog(null, ligne);
    
    String 			nom=jTable1.getModel().getValueAt(ligne, 1).toString();
    String 		created_at=jTable1.getModel().getValueAt(ligne, 2).toString();
    String 			updated_at=jTable1.getModel().getValueAt(ligne, 3).toString();
       jTextField2.setText(nom);
   
        
         } catch (SQLException ex) {
        Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
    }
  
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          position++;
      try {      
          int ligne = position;
           
                  stmt = con.createStatement();
        ResultSet resultat;
   
        resultat = stmt.executeQuery( "SELECT * FROM `entropots`");
   
        
        
       int i = 0;
while (resultat.next()) {
 
i++;
}
i--;



if(position==i){
position=1;
}




    //  JOptionPane.showMessageDialog(null, ligne);
    
    String 			Nom=jTable1.getModel().getValueAt(ligne, 1).toString();
    String 		created_at=jTable1.getModel().getValueAt(ligne, 2).toString();
    String 				updated_at	=jTable1.getModel().getValueAt(ligne, 3).toString();
    
       jTextField2.setText(Nom);
   
   
        
         } catch (SQLException ex) {
        Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         try { 
        stmt = con.createStatement();
        ResultSet resultat = stmt.executeQuery( "SELECT * FROM `entropots`");
        
        
       int i = 0;
while (resultat.next()) {
 
i++;

    System.out.println(i);



}
i--;
position=i;

          String 				Nom=jTable1.getModel().getValueAt(position, 1).toString();
    String 	created_at=jTable1.getModel().getValueAt(position, 2).toString();
    String 				updated_at	=jTable1.getModel().getValueAt(position, 3).toString();
   
       jTextField1.setText(Nom);
   // jTextPrenom.setText(prenom);
    //jTextVille.setText(ville);
   
    } catch (SQLException ex) {
        Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
    }
         
    //  JOptionPane.showMessageDialog(null, ligne)
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrepots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrepots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrepots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrepots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrepots().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
