/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_commercial.View;

import gestion_commercial.CONNEXION.NewCon;
import gestion_commercial.Droits.folder;
import java.awt.Container;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Collection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import javax.swing.JFileChooser;
//import org.apache.poi.xssf.usermodel.XSSFsheet;
//import org.apache.poi.xssf.usermodel.XSSFWorkbook;



/**
 *
 * @author didiy
 */
public class utilisateurs extends javax.swing.JFrame {
NewCon cnx=new NewCon();
       Connection con=cnx.getInstance();
      Statement stmt;  
    DefaultTableModel d =new DefaultTableModel();
    int selectedrow;
     PreparedStatement pst;
     ResultSet rs;
   int position=1;
    /**
     * Creates new form utilisateurs
     */
    public utilisateurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextPrenom = new javax.swing.JTextField();
        jTextVille = new javax.swing.JTextField();
        jTextProfile = new javax.swing.JTextField();
        jTextEquipe = new javax.swing.JTextField();
        jPasswordConfirm = new javax.swing.JPasswordField();
        txt_password = new javax.swing.JPasswordField();
        jTextadr = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextTel = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        cmd_add = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nom");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Prenom");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date Naissance");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ville");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Adresse");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Email");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tel");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Mot de Passe");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Confirmation MP");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Profile");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Equipe");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Activé");

        txt_username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextField2.setText("jTextField1");

        jTextPrenom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrenomActionPerformed(evt);
            }
        });

        jTextVille.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextVille.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVilleActionPerformed(evt);
            }
        });

        jTextProfile.setEnabled(false);

        jTextEquipe.setEnabled(false);

        jTextadr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextadr.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextadr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextadrActionPerformed(evt);
            }
        });

        jTextEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextEmail.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jTextTel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextTel.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Desactivé", "" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Code");

        jTextField1.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("<");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(">>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(">");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/erase-128.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/import-icon.png"))); // NOI18N
        jButton2.setText("Importer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exporte1r.png"))); // NOI18N
        jButton3.setText("Exporter");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_commercial/View/update icon.png"))); // NOI18N
        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cmd_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_16x16.gif"))); // NOI18N
        cmd_delete.setText("Delete");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
        cmd_add.setText("Add ");
        cmd_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addActionPerformed(evt);
            }
        });

        cmd_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_commercial/View/update icon.png"))); // NOI18N
        cmd_update.setText("Update");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox2PropertyChange(evt);
            }
        });

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmd_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_update, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel7)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel1))
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextPrenom)
                                                    .addComponent(txt_username)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(140, 140, 140)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))))
                                            .addComponent(jLabel12)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextVille, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextadr, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10))
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(69, 69, 69)
                                            .addComponent(jTextEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(71, 71, 71)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addComponent(jLabel12))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextadr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cmd_update)
                    .addComponent(cmd_delete)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(cmd_add, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        jTabbedPane1.addTab("Utilisateurs", jPanel1);
        jTabbedPane1.addTab("Roles", jTabbedPane2);
        jTabbedPane1.addTab("Permission", jTabbedPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      // TODO add your handling code here:
         try {
 DefaultTableModel d = new DefaultTableModel();
    Container cnt = this.getContentPane();
    JTable jtbl = new JTable(d);
      stmt = con.createStatement();
        cnt.setLayout(new FlowLayout(FlowLayout.LEFT));
      
        d.addColumn("nom");
        d.addColumn("prenom");
        d.addColumn("date_naiss");
        d.addColumn("ville");
        d.addColumn("adresse");
        d.addColumn("email");
        d.addColumn("tel");
        d.addColumn("motdepasse");
        d.addColumn("confirm_mdp");
        d.addColumn("profilee");
        d.addColumn("Equipe");
        d.addColumn("display_name");
        
          
            ResultSet resultat = stmt.executeQuery( "SELECT `compte`.`Id_compte`"
                    + ", `compte`.`nom`, `compte`.`prenom`, `compte`.`date_naiss`"
                    + ", `compte`.`ville`, `compte`.`adresse`, `compte`.`email`"
                    + ", `compte`.`tel`, `compte`.`motdepasse`"
                    + ", `roles`.name, `equipes`.`NOM`, `compte`.`display_name` "
                    + "FROM `compte`,roles,`equipes` "
                    + "WHERE `compte`.`profilee`=roles.`id` and `compte`.`Equipe`=equipes.`id`");
            jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
          
Map<Integer,String> map=new HashMap<Integer,String>();
ResultSet res = stmt.executeQuery( "SELECT * FROM `equipes`");
  
int id; 
String libelle;
while(res.next()){
   
id=res.getInt("id");
libelle=res.getString("NOM");
jComboBox2.addItem(libelle);
map.put(id,libelle);
System.out.println("KOKO");
}         
            
    
 Map<Integer,String> map1=new HashMap<Integer,String>();
 ResultSet res1 = stmt.executeQuery( "SELECT * FROM `roles`");

while(res1.next()){
   
id=res1.getInt("id");
libelle=res1.getString("name");
jComboBox3.addItem(libelle);
map1.put(id,libelle);
System.out.println("loolo");
}         
  jTextProfile.setText("");
        jTextEquipe.setText("");

       }
      
            
           
            
         catch (Exception e) {
            System.out.println(e.getMessage());
        }
   
            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {

            // do something with object

            ResultSet res;
            String nom;
            int id = 0;
            nom=jComboBox3.getSelectedItem().toString();
            try {
                stmt = con.createStatement();
                res = stmt.executeQuery( "SELECT * FROM `roles` where `name`='"+nom+"'");

                while(res.next()){

                    id=res.getInt("id");

                }
                jTextProfile.setText(String.valueOf(id));
            } catch (SQLException ex) {
                Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
            }

        }         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2PropertyChange

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {

            // do something with object

            ResultSet res;
            String nom;
            int id = 0;
            nom=jComboBox2.getSelectedItem().toString();
            try {
                stmt = con.createStatement();
                res = stmt.executeQuery( "SELECT * FROM `equipes` where `NOM`='"+nom+"'");

                while(res.next()){

                    id=res.getInt("id");

                }
                jTextEquipe.setText(String.valueOf(id));
            } catch (SQLException ex) {
                Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir mettre à jour l'enregistrement?","Mettre à jour l'enregistrement",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{

                DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
                String sql;
                if(jComboBox1.getSelectedItem().toString().equals("Active")){
                    sql= "update compte  set "
                    + "nom='"+txt_username.getText()+"',"
                    + "prenom='"+jTextPrenom.getText()+"',"
                    + " date_naiss='"+df.format(jDateChooser1.getDate())+"',"
                    + "ville='"+jTextVille.getText()+"',"
                    + "adresse='"+jTextadr.getText()+"',"
                    + "email='"+jTextEmail.getText()
                    +"',tel='"+jTextTel.getText()+"',"
                    + "motdepasse='"+txt_password.getText()+"',"
                    + "profilee='"+jTextProfile.getText()
                    +"',display_name=1 "
                    + ",Equipe='"+jTextEquipe.getText()+"' "
                    + "where Id_compte='"+jTextField1.getText()+"' ";

                    System.out.println(sql);
                }else{
                    sql= "update compte  set "
                    + "nom='"+txt_username.getText()+"',"
                    + "prenom='"+jTextPrenom.getText()+"',"
                    + " date_naiss='"+df.format(jDateChooser1.getDate())+"',"
                    + "ville='"+jTextVille.getText()+"',"
                    + "adresse='"+jTextadr.getText()+"',"
                    + "email='"+jTextEmail.getText()
                    +"',tel='"+jTextTel.getText()+"',"
                    + "motdepasse='"+txt_password.getText()+"',"
                    + "profilee='"+jTextProfile.getText()
                    +"',display_name=0 "
                    + ",Equipe='"+jTextEquipe.getText()+"' "
                    + "where Id_compte='"+jTextField1.getText()+"' ";

                    System.out.println(sql);
                }

                stmt.executeUpdate(sql);

                JOptionPane.showMessageDialog(null, "Mis à jour");

                ResultSet resultat = stmt.executeQuery( "SELECT `compte`.`Id_compte`"
                    + ", `compte`.`nom`, `compte`.`prenom`, `compte`.`date_naiss`"
                    + ", `compte`.`ville`, `compte`.`adresse`, `compte`.`email`"
                    + ", `compte`.`tel`, `compte`.`motdepasse`"
                    + ", `roles`.name, `equipes`.`NOM`, `compte`.`display_name` "
                    + "FROM `compte`,roles,`equipes` "
                    + "WHERE `compte`.`profilee`=roles.`id` and `compte`.`Equipe`=equipes.`id`");
                jTable1.setModel(DbUtils.resultSetToTableModel(resultat));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
        }
    }//GEN-LAST:event_cmd_updateActionPerformed

    private void cmd_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir ajouter un enregistrement?","Ajouter un enregistrement",JOptionPane.YES_NO_OPTION);
        if(p==0){        // TODO add your handling code here:

            try {
                stmt = con.createStatement();
                DateFormat df=new SimpleDateFormat("yyyy-MM-dd");

                DateFormat only_date=new SimpleDateFormat("dd");
                DateFormat only_month=new SimpleDateFormat("MM");
                DateFormat only_year=new SimpleDateFormat("yyyy");
                String sql;
                if(jComboBox1.getSelectedItem().toString().equals("Active")){
                    sql ="insert into compte ("
                    + "Id_compte,"
                    + "nom,"
                    + "prenom,"
                    + "date_naiss,"
                    + "ville,"
                    + "adresse,"
                    + "email,"
                    + "tel,"
                    + "motdepasse,"
                    + "profilee,"
                    + "Equipe,"
                    + "display_name)"
                    + " values ("
                    + "NULL,'"
                    +txt_username.getText()
                    +"','"
                    +jTextPrenom.getText()
                    +"','"
                    +df.format(jDateChooser1.getDate())
                    +"','"
                    +jTextVille.getText()
                    +"','"
                    +jTextadr.getText()
                    +"','"
                    +jTextEmail.getText()
                    +"',"
                    +jTextTel.getText()
                    +",'"
                    +txt_password.getPassword()
                    +"','"
                    +jTextProfile.getText()
                    +"','"
                    +jTextEquipe.getText()
                    +"',1)";

                }
                else{
                    sql ="insert into compte ("
                    + "Id_compte,"
                    + "nom,"
                    + "prenom,"
                    + "date_naiss,"
                    + "ville,"
                    + "adresse,"
                    + "email,"
                    + "tel,"
                    + "motdepasse,"
                    + "profilee,"
                    + "Equipe,"
                    + "display_name)"
                    + " values ("
                    + "NULL,'"
                    +txt_username.getText()
                    +"','"
                    +jTextPrenom.getText()
                    +"','"
                    +df.format(jDateChooser1.getDate())
                    +"','"
                    +jTextVille.getText()
                    +"','"
                    +jTextadr.getText()
                    +"','"
                    +jTextEmail.getText()
                    +"',"
                    +jTextTel.getText()
                    +",'"
                    +txt_password.getPassword()
                    +"','"
                    +jTextProfile.getText()
                    +"','"
                    +jTextEquipe.getText()
                    +"',1)";

                }

                stmt.executeUpdate(sql);

                JOptionPane.showMessageDialog(null,"Les données sont enregistrées avec succès");
                ResultSet resultat = stmt.executeQuery( "SELECT `compte`.`Id_compte`"
                    + ", `compte`.`nom`, `compte`.`prenom`, `compte`.`date_naiss`"
                    + ", `compte`.`ville`, `compte`.`adresse`, `compte`.`email`"
                    + ", `compte`.`tel`, `compte`.`motdepasse`"
                    + ", `roles`.name, `equipes`.`NOM`, `compte`.`display_name` "
                    + "FROM `compte`,roles,`equipes` "
                    + "WHERE `compte`.`profilee`=roles.`id` and `compte`.`Equipe`=equipes.`id`");
                jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
            }
            catch (Exception e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_cmd_addActionPerformed

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:

        int p = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir supprimer l'enregistrement?","Supprimer",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql ="delete from compte where Id_compte=?";
            try{
                pst=con.prepareStatement(sql);
                pst.setString(1, jTextField1.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Enregistrement supprimé");
                ResultSet resultat = stmt.executeQuery( "SELECT `compte`.`Id_compte`"
                    + ", `compte`.`nom`, `compte`.`prenom`, `compte`.`date_naiss`"
                    + ", `compte`.`ville`, `compte`.`adresse`, `compte`.`email`"
                    + ", `compte`.`tel`, `compte`.`motdepasse`"
                    + ", `roles`.name, `equipes`.`NOM`, `compte`.`display_name` "
                    + "FROM `compte`,roles,`equipes` "
                    + "WHERE `compte`.`profilee`=roles.`id` and `compte`.`Equipe`=equipes.`id`");
                jTable1.setModel(DbUtils.resultSetToTableModel(resultat));

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }

        }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel d = new DefaultTableModel();
            Container cnt = this.getContentPane();
            JTable jtbl = new JTable(d);
            stmt = con.createStatement();
            cnt.setLayout(new FlowLayout(FlowLayout.LEFT));

            d.addColumn("nom");
            d.addColumn("prenom");
            d.addColumn("date_naiss");
            d.addColumn("ville");
            d.addColumn("adresse");
            d.addColumn("email");
            d.addColumn("tel");
            d.addColumn("motdepasse");
            d.addColumn("confirm_mdp");
            d.addColumn("profilee");
            d.addColumn("Equipe");
            d.addColumn("display_name");

            ResultSet resultat = stmt.executeQuery( "SELECT `compte`.`Id_compte`"
                + ", `compte`.`nom`, `compte`.`prenom`, `compte`.`date_naiss`"
                + ", `compte`.`ville`, `compte`.`adresse`, `compte`.`email`"
                + ", `compte`.`tel`, `compte`.`motdepasse`"
                + ", `roles`.name, `equipes`.`NOM`, `compte`.`display_name` "
                + "FROM `compte`,roles,`equipes` "
                + "WHERE `compte`.`profilee`=roles.`id` and `compte`.`Equipe`=equipes.`id`");
            jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
        }

        catch (Exception e) {
            System.out.println(e.getMessage());
        }

        this.pack();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            int status = chooser.showOpenDialog(null);
            if (status == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                if (file == null) {
                    return;
                }

                String fileName = chooser.getSelectedFile().getAbsolutePath().toString();

                folder filles=new folder();
                //Read an Excel File and Store in a Vector
                Vector dataHolder=filles.readExcelFile(fileName);
                //Print the data read

                filles.printCellDataToConsole(dataHolder);

            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_username.setText("");
        txt_password.setText("");
        jTextPrenom.setText("");

        jTextVille.setText("");
        jTextadr.setText("");
        jTextEmail.setText("");
        jTextTel.setText("");

        txt_password.setText("");
        jPasswordConfirm.setText("");

        jTextProfile.setText("");
        jTextEquipe.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        position++;
        try {
            int ligne = position;

            stmt = con.createStatement();
            ResultSet resultat;

            resultat = stmt.executeQuery( "SELECT * FROM `compte`");

            int i = 0;
            while (resultat.next()) {

                i++;
            }
            i--;

            if(position==i){
                position=1;
            }

            //  JOptionPane.showMessageDialog(null, ligne);

            String 	nom=jTable1.getModel().getValueAt(ligne, 1).toString();
            String 	prenom=jTable1.getModel().getValueAt(ligne, 2).toString();
            String 	date_naiss	=jTable1.getModel().getValueAt(ligne, 3).toString();
            String 	ville=jTable1.getModel().getValueAt(ligne, 4).toString();
            String 	adresse=jTable1.getModel().getValueAt(ligne, 5).toString();
            String 	email	=jTable1.getModel().getValueAt(ligne, 6).toString();
            String      tel=jTable1.getModel().getValueAt(ligne, 7).toString();
            String 	nom_utilis	=jTable1.getModel().getValueAt(ligne, 8).toString();
            String 	motdepasse	=jTable1.getModel().getValueAt(ligne, 9).toString();
            String 	confirm_mdp=jTable1.getModel().getValueAt(ligne,0).toString();

            String 	profilee=jTable1.getModel().getValueAt(ligne,0).toString();
            String 	Equipe=jTable1.getModel().getValueAt(ligne,0).toString();
            String 	display_name=jTable1.getModel().getValueAt(ligne,0).toString();
            txt_username.setText(nom);
            jTextPrenom.setText(prenom);
            jTextVille.setText(ville);
            jTextadr.setText(adresse);
            jTextEmail.setText(email);
            jTextTel.setText(tel);
            txt_password.setText(motdepasse);
            jPasswordConfirm.setText(confirm_mdp);
            jTextProfile.setText(profilee);
            jTextEquipe.setText(Equipe);
            jComboBox1.setSelectedItem(display_name);

        } catch (SQLException ex) {
            Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        try {
            stmt = con.createStatement();
            ResultSet resultat = stmt.executeQuery( "SELECT * FROM `compte`");

            int i = 0;
            while (resultat.next()) {

                i++;

                System.out.println(i);

            }
            i--;
            position=i;

            String 	nom=jTable1.getModel().getValueAt(position, 1).toString();
            String 	prenom=jTable1.getModel().getValueAt(position, 2).toString();
            String 	date_naiss=jTable1.getModel().getValueAt(position, 3).toString();
            String 	ville=jTable1.getModel().getValueAt(position, 4).toString();
            String 	adresse=jTable1.getModel().getValueAt(position, 5).toString();
            String 	email	=jTable1.getModel().getValueAt(position, 6).toString();
            String      tel=jTable1.getModel().getValueAt(position, 7).toString();
            String 	nom_utilis=jTable1.getModel().getValueAt(position, 8).toString();
            String 	motdepasse=jTable1.getModel().getValueAt(position, 9).toString();
            String 	confirm_mdp=jTable1.getModel().getValueAt(position,0).toString();
            String 	profilee=jTable1.getModel().getValueAt(position,0).toString();
            String 	Equipe=jTable1.getModel().getValueAt(position,0).toString();
            String 	display_name=jTable1.getModel().getValueAt(position,0).toString();
            txt_username.setText(nom);
            jTextPrenom.setText(prenom);
            jTextVille.setText(ville);
            jTextadr.setText(adresse);
            jTextEmail.setText(email);
            jTextTel.setText(tel);
            txt_password.setText(motdepasse);
            jPasswordConfirm.setText(confirm_mdp);
            jTextProfile.setText(profilee);
            jTextEquipe.setText(Equipe);
            jComboBox1.setSelectedItem(display_name);
        } catch (SQLException ex) {
            Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
        }

        //  JOptionPane.showMessageDialog(null, ligne);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int ligne = 0;
        //  JOptionPane.showMessageDialog(null, ligne);

        String 	nom=jTable1.getModel().getValueAt(ligne, 1).toString();
        String 	prenom=jTable1.getModel().getValueAt(ligne, 2).toString();
        String 	date_naiss=jTable1.getModel().getValueAt(ligne, 3).toString();
        String 	ville=jTable1.getModel().getValueAt(ligne, 4).toString();
        String 	adresse=jTable1.getModel().getValueAt(ligne, 5).toString();
        String 	email	=jTable1.getModel().getValueAt(ligne, 6).toString();
        String      tel=jTable1.getModel().getValueAt(ligne, 7).toString();
        String 	motdepasse	=jTable1.getModel().getValueAt(ligne, 9).toString();
        String 	confirm_mdp=jTable1.getModel().getValueAt(ligne,0).toString();
        String 	profilee=jTable1.getModel().getValueAt(ligne,0).toString();
        String 	Equipe=jTable1.getModel().getValueAt(ligne,0).toString();
        String 	display_name=jTable1.getModel().getValueAt(ligne,0).toString();
        txt_username.setText(nom);
        jTextPrenom.setText(prenom);
        jTextVille.setText(ville);
        jTextadr.setText(adresse);
        jTextEmail.setText(email);
        jTextTel.setText(tel);
        txt_password.setText(motdepasse);
        jPasswordConfirm.setText(confirm_mdp);
        jTextProfile.setText(profilee);
        jTextEquipe.setText(Equipe);
        jComboBox1.setSelectedItem(display_name);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        position--;
        try {
            int ligne = position;

            stmt = con.createStatement();
            ResultSet resultat;

            resultat = stmt.executeQuery( "SELECT * FROM `compte`");

            int i = 0;
            while (resultat.next()) {

                i++;
            }
            i--;

            if(position==0){
                position=i;
            }

            //  JOptionPane.showMessageDialog(null, ligne);

            String 			nom=jTable1.getModel().getValueAt(ligne, 1).toString();
            String 	prenom=jTable1.getModel().getValueAt(ligne, 2).toString();
            String 				date_naiss	=jTable1.getModel().getValueAt(ligne, 3).toString();
            String 				ville=jTable1.getModel().getValueAt(ligne, 4).toString();
            String 	adresse=jTable1.getModel().getValueAt(ligne, 5).toString();
            String 			email	=jTable1.getModel().getValueAt(ligne, 6).toString();
            String tel=jTable1.getModel().getValueAt(ligne, 7).toString();
            String 				nom_utilis	=jTable1.getModel().getValueAt(ligne, 8).toString();
            String 					motdepasse	=jTable1.getModel().getValueAt(ligne, 9).toString();
            String 	confirm_mdp=jTable1.getModel().getValueAt(ligne,0).toString();

            String 	profilee=jTable1.getModel().getValueAt(ligne,0).toString();
            String 	Equipe=jTable1.getModel().getValueAt(ligne,0).toString();
            String 		display_name=jTable1.getModel().getValueAt(ligne,0).toString();
            txt_username.setText(nom);
            jTextPrenom.setText(prenom);
            jTextVille.setText(ville);
            jTextadr.setText(adresse);
            jTextEmail.setText(email);
            jTextTel.setText(tel);
            txt_password.setText(motdepasse);
            jPasswordConfirm.setText(confirm_mdp);

            jTextProfile.setText(profilee);
            jTextEquipe.setText(Equipe);
            jComboBox1.setSelectedItem(display_name);

        } catch (SQLException ex) {
            Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ligne = jTable1.getSelectedRow();
        //  JOptionPane.showMessageDialog(null, ligne);
        jTextField1.setText(jTable1.getModel().getValueAt(ligne,0).toString());
        txt_username.setText(jTable1.getModel().getValueAt(ligne, 1).toString());
        jTextPrenom.setText(jTable1.getModel().getValueAt(ligne, 2).toString());
        //  jDateChooser1.setText(jTable1.getModel().getValueAt(ligne, 3).toString());
        jTextVille.setText(jTable1.getModel().getValueAt(ligne, 4).toString());
        jTextadr.setText(jTable1.getModel().getValueAt(ligne, 5).toString());
        jTextEmail.setText(jTable1.getModel().getValueAt(ligne, 6).toString());
        jTextTel.setText(jTable1.getModel().getValueAt(ligne, 7).toString());
        txt_password.setText(jTable1.getModel().getValueAt(ligne, 8).toString());
        jTextEquipe.setText(jTable1.getModel().getValueAt(ligne, 11).toString());
        jTextProfile.setText(jTable1.getModel().getValueAt(ligne, 10).toString());

        try {
            String dateValue = jTable1.getModel().getValueAt(ligne, 3).toString(); // What ever column
            java.util.Date date;
            date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
            jDateChooser1.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(jTable1.getModel().getValueAt(ligne, 12).toString().equals("true")){

            jComboBox1.setSelectedItem("Active");

        }else{

            jComboBox1.setSelectedItem("Desactivé");
        }
        System.out.println("gestion_commercial.View.Roles_view.jTable1MouseClicked()");
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextadrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextadrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextadrActionPerformed

    private void jTextVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVilleActionPerformed

    private void jTextPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrenomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utilisateurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_add;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordConfirm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEquipe;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextPrenom;
    private javax.swing.JTextField jTextProfile;
    private javax.swing.JTextField jTextTel;
    private javax.swing.JTextField jTextVille;
    private javax.swing.JTextField jTextadr;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
